<form action="index.php?page=account&amp;action=login" method="post">
    <ul>
        <li>
            <label>Username</label>
            <input type="text" name="username" placeholder="username">
        </li>
        <li>
            <label>Password</label>
            <input type="password" name="password" placeholder="password">
        </li>
    </ul>
    <input type="submit" value="Login">
    <p class="error">[@messages]</p>
</form>
<p class="formHint">
    <a href="index.php?page=account&amp;action=register">New user? Register here.</a>
</p>
