<form action="index.php?page=account&amp;action=register" method="post">
    <ul>
        <li>
            <label>Username</label>
            <input type="text" name="username" placeholder="username" >
        </li>
        <li>
            <label>Password</label>
            <input type="password" name="password" placeholder="password">
        </li>
    </ul>
    <input type="submit" value="Register">
    <p class="error">[@error]</p>
</form>
<p class="formHint">[@hint]</p>